In [160]:
import pandas as pd
import numpy as np
import seaborn as sns

In [162]:
#Here are all the data file names
#220211_2F1M_final_metadata

#220211_2F1M_final_X201217_Lane1_append
#220211_2F1M_final_X201217_Lane2_append

#220211_2F1M_final_X210125_Lane1_append
#220211_2F1M_final_X210125_Lane2_append

#220211_2F1M_final_X210126_Lane1_append
#220211_2F1M_final_X210126_Lane3_append
#220211_2F1M_final_X210126_Lane4_append

#220211_2F1M_final_X210513_Lane3_append
#220211_2F1M_final_X210513_Lane4_append

#220211_2F1M_final_X210527_Lane1_append
#220211_2F1M_final_X210527_Lane2_append
#220211_2F1M_final_X210527_Lane3_append
#220211_2F1M_final_X210527_Lane4_append

#220211_2F1M_final_X210602_Lane1_append
#220211_2F1M_final_X210602_Lane2_append


#For every different Lane 1 data - that is a different kind of pairing oxytocin mutant w/ WT or WT w/ WT


#220211_2M1F_NaiveChoice_metadata

#220211_2M1F_NaiveChoice_X210225_Lane1_append
#220211_2M1F_NaiveChoice_X210225_Lane2_append
#220211_2M1F_NaiveChoice_X210225_Lane3_append
#220211_2M1F_NaiveChoice_X210225_Lane4_append

#220211_2M1F_NaiveChoice_X210226_Lane1_append
#220211_2M1F_NaiveChoice_X210226_Lane2_append
#220211_2M1F_NaiveChoice_X210226_Lane4_append

#220211_2M1F_NaiveChoice_X210318_Lane1_append
#220211_2M1F_NaiveChoice_X210318_Lane2_append
#220211_2M1F_NaiveChoice_X210318_Lane4_append

#220211_2M1F_NaiveChoice_X210401_Lane1_append
#220211_2M1F_NaiveChoice_X210401_Lane2_append
#220211_2M1F_NaiveChoice_X210401_Lane4_append

#220211_2M1F_NaiveChoice_X210824_Lane2_append
#220211_2M1F_NaiveChoice_X210824_Lane3_append
#220211_2M1F_NaiveChoice_X210824_Lane4_append

In [164]:
#Here we take the naive choice data and make it into Pd Data Frames

NCmetadata = pd.read_csv('220211_2M1F_NaiveChoice_metadata.csv')
#thinking that it would be worth it to label the variables to correlate w/ metadata
X210225_Lane1_append = pd.read_csv('220211_2M1F_NaiveChoice_X210225_Lane1_append.csv')
X210225_Lane2_append = pd.read_csv('220211_2M1F_NaiveChoice_X210225_Lane2_append.csv')
X210225_Lane3_append = pd.read_csv('220211_2M1F_NaiveChoice_X210225_Lane3_append.csv')
X210225_Lane4_append = pd.read_csv('220211_2M1F_NaiveChoice_X210225_Lane4_append.csv')
X210226_Lane1_append = pd.read_csv('220211_2M1F_NaiveChoice_X210226_Lane1_append.csv')
X210226_Lane2_append = pd.read_csv('220211_2M1F_NaiveChoice_X210226_Lane2_append.csv')
#X210226_Lane3_append = pd.read_csv(.csv)
X210226_Lane4_append = pd.read_csv('220211_2M1F_NaiveChoice_X210226_Lane4_append.csv')
X210318_Lane1_append = pd.read_csv('220211_2M1F_NaiveChoice_X210318_Lane1_append.csv')
X210318_Lane2_append = pd.read_csv('220211_2M1F_NaiveChoice_X210318_Lane2_append.csv')
X210318_Lane4_append = pd.read_csv('220211_2M1F_NaiveChoice_X210318_Lane4_append.csv')
X210401_Lane1_append = pd.read_csv('220211_2M1F_NaiveChoice_X210401_Lane1_append.csv')
X210401_Lane2_append = pd.read_csv('220211_2M1F_NaiveChoice_X210401_Lane2_append.csv')
X210401_Lane4_append = pd.read_csv('220211_2M1F_NaiveChoice_X210401_Lane4_append.csv')
X210824_Lane2_append = pd.read_csv('220211_2M1F_NaiveChoice_X210824_Lane2_append.csv')
X210824_Lane3_append = pd.read_csv('220211_2M1F_NaiveChoice_X210824_Lane3_append.csv')
X210824_Lane4_append = pd.read_csv('220211_2M1F_NaiveChoice_X210824_Lane4_append.csv')

naive_data = [X210225_Lane1_append,
              X210225_Lane2_append,
              X210225_Lane3_append,
              X210225_Lane4_append,
              X210226_Lane1_append,
              X210226_Lane2_append,
              #X210226_Lane3_append,
              X210226_Lane4_append,
              X210318_Lane1_append,
              X210318_Lane2_append,
              X210318_Lane4_append,
              X210401_Lane1_append,
              X210401_Lane2_append,
              X210401_Lane4_append,
              X210824_Lane2_append,
              X210824_Lane3_append,
              X210824_Lane4_append,
             ]

#In order to read this, I needed to download and move the csv file into the same folder as my Github projects
#and then I could reference it by name
NCmetadata

               File.name     Left    Right   Sex
0   X210225_Lane1_append       WT  Oxtr-/-  2M1F
1   X210225_Lane2_append       WT       WT  2M1F
2   X210225_Lane3_append  Oxtr-/-       WT  2M1F
3   X210225_Lane4_append       WT       WT  2M1F
4   X210226_Lane1_append  Oxtr-/-       WT  2M1F
5   X210226_Lane2_append       WT       WT  2M1F
6   X210226_Lane3_append       WT  Oxtr+/-  2M1F
7   X210226_Lane4_append  Oxtr-/-       WT  2M1F
8   X210318_Lane1_append       WT       WT  2M1F
9   X210318_Lane2_append       WT  Oxtr-/-  2M1F
10  X210318_Lane4_append       WT  Oxtr-/-  2M1F
11  X210401_Lane1_append       WT       WT  2M1F
12  X210401_Lane2_append  Oxtr-/-       WT  2M1F
13  X210401_Lane4_append  Oxtr-/-       WT  2M1F
14  X210824_Lane2_append       WT       WT  2M1F
15  X210824_Lane3_append       WT       WT  2M1F
16  X210824_Lane4_append       WT       WT  2M1F

In [108]:
#I want to be able to do the amount of time spent in each quadrant and in contact with each partner
#I can do this by subtracting and appending in a new column - I think or create a whole new data frame honestly

#this is a test to determine what the math looks like for calculating time spent

row1 = X210225_Lane1_append.loc[0]
time_spent_center = row1[2] - row1[1]
time_spent_right = row1[4] - row1[3]
time_spent_left = row1[8] - row1[7]
time_contact_right = row1[6] - row1[5]
time_contact_left = row1[10] - row1[9]
time_spentrow1 = [time_spent_center, time_spent_right, time_spent_left, time_contact_right, time_contact_left]

In [129]:
def time_spent(dataset):
    time_spent_center = []
    time_spent_right = []
    time_spent_left = []
    time_contact_right = []
    time_contact_left = []
    i = 0
    for i in range(0,len(dataset),1):
        row = dataset.loc[i]
        timespentcenter = row[2] - row[1]
        timespentright = row[4] - row[3]
        timespentleft = row[8]-row[7]
        timecontactright = row[6]-row[5]
        timecontactleft = row[10]-row[9]
        time_spent_center.append(timespentcenter)
        time_spent_right.append(timespentright)
        time_spent_left.append(timespentleft)
        time_contact_right.append(timecontactright)
        time_contact_left.append(timecontactleft)
    total_time_center = np.nansum(time_spent_center)
    total_time_right = np.nansum(time_spent_right)
    total_time_left = np.nansum(time_spent_left)
    total_contact_right = np.nansum(time_contact_right)
    total_contact_left = np.nansum(time_contact_left)
    return [total_time_center, total_time_right, total_time_left, total_contact_right, total_contact_left]

#I've created a bunch of lists with time spent in center/left/right/contact right and contact left
#I'm not sure this was the right approach because I want to append it as a column instead

In [176]:
def function_time_spent_center(dataset):
    time_spent_center = []
    for i in range (0, len(dataset),1):
        row = dataset.loc[i]
        timespentcenter = row[2]-row[1]
        time_spent_center.append(timespentcenter)
    total_time_center = np.nansum(time_spent_center)
    return total_time_center

def function_time_spent_right(dataset):
    time_spent_right = []
    for i in range(0, len(dataset),1):
        row = dataset.loc[i]
        timespentright = row[4] - row[3]
        time_spent_right.append(timespentright)
    total_time_right = np.nansum(time_spent_right)
    return total_time_right

def function_time_spent_left(dataset):
    time_spent_left = []
    for i in range(0, len(dataset),1):
        row = dataset.loc[i]
        timespentleft = row[8] - row[7]
        time_spent_left.append(timespentleft)
    total_time_left = np.nansum(time_spent_left)
    return total_time_left

def function_time_contact_right(dataset):
    time_contact_right = []
    for i in range(0, len(dataset),1):
        row = dataset.loc[i]
        timecontactright = row[6] - row[5]
        time_contact_right.append(timecontactright)
    total_contact_right = np.nansum(time_contact_right)
    return total_contact_right
    
def function_time_contact_left(dataset):
    time_contact_left = []
    for i in range(0, len(dataset),1):
        row = dataset.loc[i]
        timecontactleft = row[10] - row[9]
        time_contact_left.append(timecontactleft)
    total_contact_left = np.nansum(time_contact_left)
    return total_contact_left

In [170]:
NCmetadata

               File.name     Left    Right   Sex
0   X210225_Lane1_append       WT  Oxtr-/-  2M1F
1   X210225_Lane2_append       WT       WT  2M1F
2   X210225_Lane3_append  Oxtr-/-       WT  2M1F
3   X210225_Lane4_append       WT       WT  2M1F
4   X210226_Lane1_append  Oxtr-/-       WT  2M1F
5   X210226_Lane2_append       WT       WT  2M1F
6   X210226_Lane3_append       WT  Oxtr+/-  2M1F
7   X210226_Lane4_append  Oxtr-/-       WT  2M1F
8   X210318_Lane1_append       WT       WT  2M1F
9   X210318_Lane2_append       WT  Oxtr-/-  2M1F
10  X210318_Lane4_append       WT  Oxtr-/-  2M1F
11  X210401_Lane1_append       WT       WT  2M1F
12  X210401_Lane2_append  Oxtr-/-       WT  2M1F
13  X210401_Lane4_append  Oxtr-/-       WT  2M1F
14  X210824_Lane2_append       WT       WT  2M1F
15  X210824_Lane3_append       WT       WT  2M1F
16  X210824_Lane4_append       WT       WT  2M1F

In [177]:
#I want to make a new table where the row labels are the data files and the columns are the time spents
tc = []
tr = []
tl = []
tcr = []
tcl = []
for z in range(0, len(naive_data),1):
    tc.append(function_time_spent_center(naive_data[z]))
    tr.append(function_time_spent_right(naive_data[z]))
    tl.append(function_time_spent_left(naive_data[z]))
    tcr.append(function_time_contact_right(naive_data[z]))
    tcl.append(function_time_contact_left(naive_data[z]))

In [178]:
print (tc)
print (tr)
print (tl)
print (tcr)
print (tcl)

[2177.2720000000118, 5884.999999999964, 4690.919000000022, 4339.099000000004, 3152.2399999999825, 3353.1780000000044, 2933.942, 4435.85099999997, 110399.10699999999, 2572.5269999999946, 3511.4879999999994, 2429.301000000016, 3634.897999999985, 1238.2020000000284, 2615.726999999989, 7086.801999999996]
[2772.918999999998, 5826.462000000031, 565.2439999999841, 7915.059999999998, 2527.4560000000192, 4528.652999999991, 2442.8849999999993, 5977.4640000000345, -793203.857, 9073.723000000035, 935.1110000000019, 4112.2780000000275, 5414.006000000021, 3411.874999999992, 6941.818000000021, 5436.280000000014]
[5332.9399999999805, 2391.168999999998, 6512.220999999994, 5541.526000000016, 5770.538999999984, 2990.899000000006, 2616.9659999999844, 28.599999999998545, -1084408.893, 25321.13899999996, 5030.090999999995, 1.733999999999451, 432.06700000000376, 4064.4209999999857, 4347.913000000018, 4716.245999999983]
[10079.171999999991, 3761.270999999972, 2223.534000000004, 184.02799999998908, 7992.208999999988, 6946.839000000005, 11991.640000000003, 2628.9520000000007, 1014942.9239999999, 1605.5620000000013, 5711.687000000027, 5679.432000000006, 12078.129999999994, 12138.396999999997, 6452.748999999982, 1339.3859999999981]
[965.8250000000196, 1954.600000000024, 7047.250999999995, 1692.1439999999948, 2144.0220000000227, 3390.0650000000037, 1602.9340000000113, 5851.882999999996, 1312653.864, 3746.3590000000104, 6411.622999999976, 8516.558999999968, 40.865999999996745, 746.8369999999966, 1241.392999999991, 2849.4890000000064]

In [179]:
# Adding a new column using loc method
#
NCmetadata.loc[:, ["Time spent in center"]] = tc
NCmetadata.loc[:, ["Time spent in right"]] = tr
NCmetadata.loc[:, ["Time spent in left"]] = tl
NCmetadata.loc[:, ["Time contact right"]] = tcr
NCmetadata.loc[:, ["Time contact left"]] = tcl

ValueError: Must have equal len keys and value when setting with an iterable